### ISSUE TITLE
env variable to let the rancher environment name be a part of the fqdn of the services

### ISSUE THREAD

**Issue by digitalLumberjack** [rawmind0/rancher-traefik#10]
It would be cool to have a switch that puts the environment name in the fqdn of the services.
My needs are to get multiple environments having same services and stacks like : 
- www.app.prod.company.com
- www.app.preprod.company.com
- www.app.dev.company.com

And that would be on 3 different traefik instances, on 3 rancher env.

I made that hardcoded for my needs, as i cannot find the time right now to make a PR, but this issue might be a reminder when i will have time :)
https://github.com/digitalLumberjack/rancher-traefik/commit/f136307d4b035101f1df7baa14a4983fd0d9e5fe

**Comment by rawmind0** [comment]
Hi @digitalLumberjack ...

i think you could do the same without the needed to modify anything in rancher-traefik. Don't you think that it would be easier to modify the traefik.domain label in the services that wants to be exposed?? I mean, i don't know how you are deploying, but it seems that it would be easier to modify the setting of traefik.domain label in the services catalog package or deploy scripts....
When i add the feat to accept multiple values in traefik.domain, this was one of the user histories. ;)

Thanks for your feedback and your ideas...Unfortunately, in i'm like you in terms of time...Good reminder... :)

**Comment by digitalLumberjack** [comment]
You got a point :) My needs would be a little too much different of your vision of the project :) I think i would like to configure all on the traefik service :)

**Comment by digitalLumberjack** [comment]
Thank you for the work though :)

**Comment by rawmind0** [comment]
I understand your point... I was thinking in it before to get one or another way.... 

This is my rational, if it could helps you....
I thought the service package to be shared between multiples services. In that way, centralize policies seems a bad idea. Although in terms of microservices topics, i think it's a deployment responsibility to say if the service needs to be exposed or not, which protocol it uses and what its name is.  In this way, you could delegate this responsibility to every development team, but traefik have the responsibility to get the service config and exposed it, and to assure some things, for example that names are unique. :)

I think it would be nice to make a switch to "limit" the search scope of traefik and be able to deploy it as a non global service. It would expose only services from one stack, for example. It would provide support to other visions of the project. :P

I like the idea....but no time right now...
