### ISSUE TITLE
Error generating rules.toml with version 0.3.4-1 

### ISSUE THREAD

**Issue by fabiorauber** [rawmind0/rancher-traefik#12]
When using the image rawmind/rancher-traefik:0.3.4-1, the file rules.toml does not get generated by confd:

`/opt/tools/confd/bin/confd[17]: ERROR template: rules.toml.tmpl:16:146: executing "rules.toml.tmpl" at <getv (printf "/stack...>: error calling getv: key does not exist: /stacks/xxx/services/yyy/containers/stacks/health_state`

Using version 0.3.4 solves the problem. I'm using rancher in HA with version 1.1.0.

**Comment by rawmind0** [comment]
Hi @fabiorauber ,

rawmind/rancher-traefik:0.3.4-1 was builded, but it doesn't work. It was builded with confd v0.12beta that it's not working ok. I didn't update the catalog packages with this version. 

I've done two things:
- I've builded rawmind/rancher-traefik:0.3.4-3 that it's working ok (rolling back confd to v0.11)
- I've builded rawmind/alpine-traefik:1.0.2  and i've updated catalog packages to traefik v1.0.2 

Best regards...

**Comment by fabiorauber** [comment]
Thanks!

**Comment by fabiorauber** [comment]
@rawmind0, when using these images the rules.toml ends up empty:

`time="2016-08-10T13:36:20Z" level=info msg="Skipping empty Configuration for provider file"`

I noticed there is no /opt/tools/ anymore inside the traefik container.

**Comment by rawmind0** [comment]
Hi @fabiorauber..

how are you deploying?? The /opt/tools volume needs to be specified at deploy time in rancher-traefik. 
It seems that you didn't specified it. Please, take a look at alpine-traefik repo, rancher/docker-compose.yml to see it. Deploying from catalog is working ok.

Best regards...

**Comment by fabiorauber** [comment]
You're right @rawmind0. I did not update my docker-compose.yml with the /opt/tools volume. Sorry for the mistake.
