### ISSUE TITLE
Support for External Services

### ISSUE THREAD

**Issue by fabiorauber** [rawmind0/rancher-traefik#16]
It would be nice if we could add an external service to traefik, specially when it handles Let's Encrypt so easily.

**Comment by rawmind0** [comment]
What do you mean?? External services in rancher?? 

The idea sounds very good, but please, explain it a little bit more detailed...

**Comment by fabiorauber** [comment]
Exactly. It would be nice to be able to use an existing Traefik installation to serve something that works outside of Rancher, through Rancher External Services.
