### ISSUE TITLE
Does this work across multiple Rancher servers?

### ISSUE THREAD

**Issue by emcniece** [rawmind0/rancher-traefik#17]
I'm trying to set up a Docker cluster (managed by Rancher) and I am trying to find a proxy / load balancer that can move traffic between containers spread across multiple servers.

Traefik currently works well for single servers - I am currently running it as a container initiated outside of Rancher (the Rancher Traefik catalog instance didn't work) and it is watching Docker socket changes and routing traffic nicely. The downside is that I have to start a new Traefik container on each server, and then my external DNS has to point to that server's IP address, so then the containers running on that server can never leave that server. This kills Rancher's scaling capability.

I think the advantage of the rancher-traefik setup is that Traefik can use Rancher's DNS instead of Docker's DNS, so it has access to the entire Rancher system. If this is the case, I should be able to point my external DNS to a single Rancher server (which hosts the Traefik container) and hopeully Traefik will route traffic around to the Rancher system containers. 

Is this how it is supposed to work? Is rancher-traefik able to route traffic to hosts other than itself?

**Comment by rawmind0** [comment]
Hi @emcniece,

yes you are right. Rancher-traefik integrates traefik with rancher directly not through docker socket. You could have traefik running in your hosts (one or many) and traffic will be routed to your services, no matter where they would be running. 

If you run traefik in more than one host (controlled by the host label), the external dns has to have round robin entries directed to all your host that run traefik. Wildcard dns would be another option. 

The last version of rancher-traefik is published in my personal catalog, that you could add to your rancher. 
https://github.com/rawmind0/service-catalog 

Best regards....
