### ISSUE TITLE
Override stack name in domain name generation

### ISSUE THREAD

**Issue by fabiorauber** [rawmind0/rancher-traefik#18]
I have a situation where using _service_name.stack_name.domain_ is problematic: I need to have _svc.foo.bar.com_ and _svc.foo.baz.com_ published, each with its own container and stack. 

In addition, I also have _adm.foo.bar.com_ and _adm.foo.baz.com_, so _traefik.enable = stack_ is not an option. Without replacing stack_name, I would need to have two "foo" stacks, and it is not possible.

@rawmind0, what do you think of having a stack_name_override option?

**Comment by rawmind0** [comment]
Hi @fabiorauber , I perfectly understand your point. 

Many people ask for the stack_name or service_name overriding. As traefik package scope is to work as an "global" services, you have to assure unique name in the frontend filters. The idea was control it, with service_name.stack_name (assured by rancher).

I have to think how to best resolve it, giving a point of freedom with the names and still assuring unique name. 

I was thinking to limit the search scope of traefik, to not to be a "global" service, but it has any issues too......

Any idea about that would be welcomed... :)

Besta regards....

**Comment by fabiorauber** [comment]
Hi @rawmind0, 

I think an override option would be the only choice in this kind of situation. The stack_name, in that case, could be overridden by the user, and the user would then be responsible for ensuring uniqueness. So the stack names could be "foo-bar" and "foo-baz" (unique) but the service could be published as "foo.bar.com" and "foo.baz.com", nonetheless.

If the concern is whether the service would stop working, we could implement a configuration validation before it is applied, so that incorrect configurations would not be applied and would render error messages. In this way, traefik would only see unique names, despite what the user tried to do.

**Comment by emcniece** [comment]
I'm also in need of this feature. `traefik.enable` seems like a nice place to add this:

```
traefik.enable = < true | stack | manual | false >
```

Perhaps in "manual" mode the stack name could be set to the exact contents of the `traefik.domain` parameter?

**Comment by emcniece** [comment]
Looks like this idea is covered already in a PR: https://github.com/rawmind0/rancher-traefik/pull/14 and https://github.com/rawmind0/rancher-traefik/pull/6

**Comment by emcniece** [comment]
@rawmind0 it seems that at some point developers or power users need a bit of flexibility to override. If this is true, it should be up to that developer to ensure that their system doesn't have conflicts.

Unfortunately that also probably means more support tickets :\ (like from myself)

**Comment by rawmind0** [comment]
I agree with you @emcniece ...

I'm working to provide a solution to that... :P

**Comment by rawmind0** [comment]
Hi all...

Look at last commits... Added traefik.alias label to create host rules $traefik.alias.$traefik.domain ..
It creates host rules $service_name.$stack_name.$traefik.domain too...

May it work for you??

**Comment by Vincoll** [comment]
Hi @rawmind0, Your solution is nearly perfect.
But there is a little bug:

There is no way (or at least i did not find it) to only publish `domain.com`
I would like to create in one alias `www,,` to publish http://domain.com and http://www.domain.com

A empty alias create a "."domain.com

**Comment by duck1123** [comment]
The trick I've been using to serve foo.com is to name my stack "foo" and then set traefik.domain to just "com"

Not ideal, but it works.

**Comment by rawmind0** [comment]
@Vincoll @duck1123 , solved the little bug with last commit, 
https://github.com/rawmind0/rancher-traefik/commit/a380c2a570b2a2edc4c24effd223c6e82804d149

For `traefik.domain=domain.com` and `traefik.alias=www,` or empty  
http://domain.com and http://www.domain.com will be published. 

May it work for you?? :)

**Comment by rawmind0** [comment]
Solved with commits https://github.com/rawmind0/rancher-traefik/commit/34d62d4b0dafd7b3db92aa473081180217bb2552 https://github.com/rawmind0/rancher-traefik/commit/a380c2a570b2a2edc4c24effd223c6e82804d149 ...

Please reopen it, if you need... :)

**Comment by fabiorauber** [comment]
@rawmind0, I actually cannot use the stack_name in the final URL for my use case. Currently there is no way to keep the stack_name out, and the ACME certificate is generated based on this primary hostname.

**Comment by seb2411** [comment]
Definitely it would be nice to be able to publish only the domain with alias. Or simply to define the complete domain we want. There are no way for example to expose only a domain dev.example.com

**Comment by jrohde** [comment]
@rawmind0, first many thanks for all your work on this. Traefik and this rancher integration is really great stuff! Nevertheless I'm also having some troubles with this (specific issue):

Currently i'm using 'local' for the traefik.domain label and use the traefik.alias.fqdn for the fqdn domain i want traefik to match on. But when enabling acme in this case the 'service_name,stack_name.local' (the primary 'domain') seriously bugs the acme servers with errors like: 

> Cannot obtain certificates map[service_name.stack_name.local:acme: Error 400 - urn:acme:error:malformed - Error creating new authz :: Name does not end in a public suffix. 

Resulting in a bad reputation from my server (acme rate limits kick in ;-().
Maybe a solution can be to add a label like: 'traefik.acme.domain' (comma separate for multiple  domains) which will only be used to match on (Traefik rules) and for fetching acme certs. Domains not added to this label are never used for acme; so if you want the primary domain (service_name.stack_name.domain) to have a cert also, you have to add it here. Would something like that make sense?! I have to dig through the code syntax, but i can probably help out with a feature like this.

**Comment by stevenmunro** [comment]
Is there a workaround for this? It is a bit of a showstopper for me. I'm using v1.3.3 and traefik.domain=domain.com doesn't seem to work - it still contains the stack name

**Comment by duck1123** [comment]
Try using traefik.alias.fqdn you might still need to have the other domain rule, but that should let it match
