### ISSUE TITLE
Service Aliases as target

### ISSUE THREAD

**Issue by svensp** [rawmind0/rancher-traefik#22]
We're heavily working with rolling upgrades in our environment. This means that every new version necessarily has a new name - with revision as suffix in our case.

This is a problem with the current naming scheme of `servicename.stackname.domain` because each version would be different. Switching to stacks named `app` or `www` on the other hand would scatter microservices which belong together into multiple stacks.

Idea for a solution: allow `Service Alias`es to be the load balancing target. The `www` alias in the `application` stack with domain `com` would then become `www.application.com` and still always point to the current version.

This could also be used to substitute for the `custom name` rule for some cases.

**Comment by rawmind0** [comment]
Hi @svensp ...

Look at last commits... Added traefik.alias label to create host rules $traefik.alias.$traefik.domain ..
It creates host rules $service_name.$stack_name.$traefik.domain too...

May it work for you??

**Comment by rawmind0** [comment]
Closed due to feature already added...
https://github.com/rawmind0/rancher-traefik/commit/34d62d4b0dafd7b3db92aa473081180217bb2552
