### ISSUE TITLE
Add support for different path-based rules

### ISSUE THREAD

**Issue by xaka** [rawmind0/rancher-traefik#23]
https://docs.traefik.io/basics/#frontends:

```
Path: /products/, /articles/{category}/{id:[0-9]+}: Path adds a matcher for the URL paths. It accepts templates with zero or more URL variables enclosed by {}.

PathStrip: Same as Path but strip the given prefix from the request URL's Path.

PathPrefix: PathPrefix adds a matcher for the URL path prefixes. This matches if the given template is a prefix of the full URL path.

PathPrefixStrip: Same as PathPrefix but strip the given prefix from the request URL's Path.
```

The value (`Path`, `PathStrip`, etc.) would go to `traefik.path_mode` and default is `Path` as of now.

I'm happy to open PR if there are no objections.

**Comment by rawmind0** [comment]
Hi @xaka ... sure, more than happy to merge a PR to extend path labels. :)
 
Thanks!!

**Comment by ls-amine** [comment]
@xaka any luck with the PR, i am also interested to see your work.
thanks in advance.
