### ISSUE TITLE
Runtime remove host

### ISSUE THREAD

**Issue by potterdai** [rawmind0/rancher-traefik#24]
Hi, thank you for writing this great service.
I got a question, if I remove tag traefik_lb=true from one of the hosts, is deleting and re-instantiate a traefik service the only way to update host removal?
Thank you very much.

**Comment by rawmind0** [comment]
Hi @PotterDai .. Thanks a lot for your feedback.. :)

Unfortunatelly, i think so.. In theory, when you remove a label in one host, package would have to be rescaled, but it's only working to scale up and not down.... :(
