### ISSUE TITLE
Example rancher-catalog item

### ISSUE THREAD

**Issue by joshuacox** [rawmind0/rancher-traefik#28]
Are there any  rancher  catalog items which fully implement all the labels here?  Or at least all of them necessary to get a service exposed on an SSL domain (e.g. https://www.example.com/), and not the full 

```
http://${service_name}.${stack_name}.${traefik.domain}:${http_port}
```

I think it has to do with alias:

```
traefik.alias = www.example.com
```

but I've yet to get it to work, and was wondering if there are any good examples out there?

**Comment by joshuacox** [comment]
answered my own question, sorry about the noise, closing 

https://github.com/rawmind0/alpine-traefik/blob/master/rancher/docker-compose.yml

**Comment by joshuacox** [comment]
well, here is actually more of what I was looking for:

https://github.com/withinboredom/converser/blob/master/rancher-docker-compose.yml

**Comment by joshuacox** [comment]
and I am still very confused as all my configs seem to be getting it wrong, here is my current attempt:

https://github.com/WebHostingCoopTeam/whc-catalog/blob/master/templates/owncloud/2/docker-compose.yml#L13-L18

I'd gladly take any advice

**Comment by rawmind0** [comment]
Hi @joshuacox ....

In your current compose file, you are using different labels....

You could see the labels description at readme file, https://github.com/rawmind0/rancher-traefik/blob/master/README.md

```
    traefik.frontend.passHostHeader: 'true'
    traefik.frontend.entryPoints: https
```
These labels are not supported by the moment. Passtoheader is added automatically at traefik service, and entrypoint too. 
If you launch traefik service with enable HTTPS = true, then you could access your services by http and https.
If you launch traefik service with enable HTTPS = only, then you could access your services only by https and http get redirected to https.
If you launch traefik service with enable HTTPS = false, then you could access your services only by http.

Same for rules, host and path. 
Host rules would be autogenerated with traefik.alias and traefik.domain labels from the service. 
Path rules would be autogenerated with traefik.path* labels from the service.

Please, tell me if you need more advice... :)

**Comment by joshuacox** [comment]
well I am very close my current traefik labels look as follows:

```
    traefik.enable: true
    traefik.acme: true
    traefik.alias: ${OWNCLOUD_HOST}
    traefik.domain: ${OWNCLOUD_DOMAIN}
    traefik.port: ${PORT}
```

now I get `Service Unavailable` so at least the hostname is being set correctly now, but the logs indicate I still  have an issue:

```
1/25/2017 10:55:21 AM133.188.133.133 - - [25/Jan/2017:16:55:21 +0000] "GET / HTTP/1.1" 502 11 "" "Mozilla/5.0 (X11; Linux x86_64; rv:50.0) Gecko/20100101 Firefox/50.0" 8 "owncloud__Owncloud-WHC" "http://10.42.69.5:14080" 8ms
```

If I log into the traefik container itself and execute:

```
 wget http://10.42.69.5:14080 
Connecting to 10.42.69.5:14080 (10.42.69.5:14080)
wget: can't connect to remote host (10.42.69.5): Connection refused
```

however if I use the address of the rancherOS it works fine:

```
wget http://192.168.122.34:14080
Connecting to 192.168.122.34:14080 (192.168.122.34:14080)
index.html           100% |********************************************************************************************************************************************************************| 10601   0:00:00 ETA
```

I've got something wrong I'm sure

**Comment by joshuacox** [comment]
I had misunderstood a bit, you need to have `traefik.port` pointed to the private port, not the public port, so changing that to 80 and all good here, adding an example below.  Closing.  Thanks for the great work here.  Cheers


```
    traefik.enable: true
    traefik.acme: true
    traefik.alias: ${OWNCLOUD_HOST}
    traefik.domain: ${OWNCLOUD_DOMAIN}
    traefik.port: 80
```

https://github.com/WebHostingCoopTeam/whc-catalog/blob/master/templates/owncloud/2/docker-compose.yml#L11-L15

or add that catalog to your rancher:
https://github.com/WebHostingCoopTeam/whc-catalog/

**Comment by rawmind0** [comment]
Yes, that's it...

Thanks to use it... :)
