### ISSUE TITLE
Error while deploying service with traefik.enable = stack and ACME certificate

### ISSUE THREAD

**Issue by fabiorauber** [rawmind0/rancher-traefik#29]
_Error reading file:Near line 21 (last key parsed 'acme.domains'): Expected a top-level item to end with a new line, comment or EOF, but got '\"' instead_.

Inspecting the file:

```
[[acme.domains]]
  main = "service.domain.com""]
```

PS: Running Rancher v1.3.2.

**Comment by rawmind0** [comment]
thanks for the feedback @fabiorauber....

Is it only happens with traefik.enable=stack ??

**Comment by rawmind0** [comment]
Detected and corrected issue in commit 25fc87b

rancher-traefik:0.3.4-17

Thanks @fabiorauber  :)

**Comment by rawmind0** [comment]
Merged at rancher community catalog... :)
https://github.com/rancher/community-catalog/pull/396

Reopen it if you have some more issue...
