### ISSUE TITLE
Backend with https protocol

### ISSUE THREAD

**Issue by Vincoll** [rawmind0/rancher-traefik#30]
Hello,

I'm working on generalized http2 on my web servers.
Sadly, this pure Traefik label is not implemented:
`traefik.protocol=https`

Therefore my nginx show _400 Bad Request The plain HTTP request was sent to HTTPS port_
[https://docs.traefik.io/toml/#docker-backend](https://docs.traefik.io/toml/#docker-backend)

btw did you know if traefik will talk in http2 for its backend ?

Best regards.

**Comment by rawmind0** [comment]
Hi @Vincoll ...

You are right, traefik.protocol label was not added. 
Already added in commit https://github.com/rawmind0/rancher-traefik/commit/25fc87b2eb4e544600adc1cbba78526ec5b02eae

rancher-traefik:0.3.4-17

btw, traefik support http2 in frontend, but i'm not pretty sure in backend....

**Comment by rawmind0** [comment]
Merged at rancher community catalog... :)
https://github.com/rancher/community-catalog/pull/396

Reopen it if you have some more issue...
