### ISSUE TITLE
HTTP auth

### ISSUE THREAD

**Issue by joshuacox** [rawmind0/rancher-traefik#31]
Something I like to have for a myriad of reasons is a simple HTTP auth implemented right in the proxy.  In my nginx setups I use something like this in the host definition:

```
server {
  listen   80;
  server_name example.com;
  return 301 https://example.com$request_uri;
}
server {
  listen 443 ssl http2;
  server_name example.com;
  auth_basic "Restricted";
  auth_basic_user_file /etc/nginx/private/httplock;
  #truncating the rest of the ssl opts for brevity
}
```

Is this possible with traefik?

EDIT:  bah I've answered my own question https://github.com/containous/traefik/issues/751

feel free to close @rawmind0 but I'll leave open in case you have any thoughts on the whole matter I'd love to hear it, as I see it, an ugly workaround would be to include in your docker-compose.yml yet another nginx proxy with something similar to the above lengthening the proxy chain like so:

internet -> traefik -> httpAuth nginx -> mywebappcontainer

**Comment by rawmind0** [comment]
Hi @joshuacox ...

yes unfortunately, traefik doesn't support http auth yet. I don't really know if it's in their roadmap, but would be nice. 

More than include a nginx in the docker-compose.yml (if it's included, it would be mandatory) , i think it could be better to generate a new catalog entry with http auth, that could deploy who needs this feature. 

what do you think??

**Comment by rawmind0** [comment]
Solution to that at traefik repo PR.... https://github.com/containous/traefik/pull/1147

**Comment by joshuacox** [comment]
closing as it seems to be taken care of upstream
