### ISSUE TITLE
Sticky mode

### ISSUE THREAD

**Issue by sergiorodenas** [rawmind0/rancher-traefik#34]
Is there any way to add a service as sticky to traefik? If not, what may we do with session-driven apps?

**Comment by rawmind0** [comment]
Hi @Rodenastyle,
traefik could do it, the rancher integration not by the moment, but it's on the way.... :)

https://github.com/rawmind0/rancher-traefik/pull/33

**Comment by sergiorodenas** [comment]
@rawmind0 Yeah 👍

**Comment by rawmind0** [comment]
Already added in rawmind/rancher-traefik:0.3.4-19 

:)
