### ISSUE TITLE
passHostHeader

### ISSUE THREAD

**Issue by sergiorodenas** [rawmind0/rancher-traefik#37]
Is there any way to add a service with the rule "passHostHeader" to traefik? If not, how we get the real client IP from the apps added to traefik? (Rancher Catalog).

Edited: Thanks in advance :)

**Comment by rawmind0** [comment]
Hi @rodenastyle...
"PassHostHeader" is added automatically to all the services. You could see the tag added in traefik admi. Ui. :)

**Comment by sergiorodenas** [comment]
@rawmind0 That sounds great, thank you so much!
