### ISSUE TITLE
Load balance 1 domain to multiple services?

### ISSUE THREAD

**Issue by jmreicha** [rawmind0/rancher-traefik#39]
Is there a good way to set traefik up to load balance a number of different backend services to domain name?  For example, how do you configure test.example.com to point at test-service-a and test-service-b?  Is there some way to do it with service labels?

Apologies if this isn't the correct forum.

**Comment by rawmind0** [comment]
Hi @jmreicha....

You could do that playing with traefik service labels. Setting traefik.alias and traefik.domain equals in both services, should work.....
