### ISSUE TITLE
Basic Auth labels

### ISSUE THREAD

**Issue by joshuacox** [rawmind0/rancher-traefik#44]
Can we get a few labels for basic auth?  I have a few backends I want to limit access from the web at large, but I don't need ldap or anything like that yet.  I need this feature from traefik:

https://docs.traefik.io/user-guide/examples/#enable-basic-authentication-in-an-entrypoint

any interest in this here?

**Comment by rawmind0** [comment]
Hi @joshuacox...

yes, this feature is interesting, but it goes at https://github.com/rawmind0/alpine-traefik repo... :)

If i find time shortly, i add this feature, but so busy....Also, i accept PR anyways... :P

**Comment by rawmind0** [comment]
Moving to https://github.com/rawmind0/alpine-traefik/issues/29
