### ISSUE TITLE
No url in backends

### ISSUE THREAD

**Issue by amsdard** [rawmind0/rancher-traefik#45]
Hi, 

I've added traefik from rancher catalog. Traefik is aware of configured services (those with traefik labels), I can see them on dashboard, but none of them has servers section with url set, as a result accessing every server ends with server error. In traefik logs I see requests which I make to my services, but thats it. I've turned debugging on, but no more info is shown ie. why backends have no ip/url.

Any idea what I have might done wrong? I'm using rancher 1.5.5 and docker 12.6

Rules config:
```
[backends]
  [backends.hello__koszi]
    [backends.hello__koszi.circuitbreaker]
      expression = "NetworkErrorRatio() > 0.5"
    [backends.hello__koszi.LoadBalancer]
      method = "drr"
  [backends.tomcat__sirius]
    [backends.tomcat__sirius.circuitbreaker]
      expression = "NetworkErrorRatio() > 0.5"
    [backends.tomcat__sirius.LoadBalancer]
      method = "drr"
[frontends]
  [frontends.hello__koszi]
    backend = "hello__koszi"
    passHostHeader = true
    priority =  5
    [frontends.hello__koszi.routes.service]
      rule = "Host:hello.koszi.app.example.io,tutum.app.example.io;"
  [frontends.tomcat__sirius]
    backend = "tomcat__sirius"
    passHostHeader = true
    priority =  5
    [frontends.tomcat__sirius.routes.service]
      rule = "Host:tomcat.sirius.app.example.io,sirius2.app.example.io;"
```

**Comment by rawmind0** [comment]
Hi @amsdard ...

Have your services healthcheck configured?? Traefik only add backends that has a healthy state...So healthcheks are mandatory....

**Comment by amsdard** [comment]
After adding healthcheck it works like a charm! Thanks for quick response!
