### ISSUE TITLE
Default domain

### ISSUE THREAD

**Issue by amsdard** [rawmind0/rancher-traefik#46]
Hi, is it possible to setup a default domain just like in traefik docs?

When I run traefik with --docker.domain=app.example.io then in my container I setup traefik.alias=web it is not accessible under web.app.example.io. To make it work I need to add traefik.domain=app.example.io. 

Is there any way to overcome this?

**Comment by rawmind0** [comment]
Hi @amsdard ...

This traefik version is not integrated with rancher with the new traefik feature. Default domain option is not implemented, traefik.domain is needed. 

It could be implemented but it isn't by the moment. Happy for a PR.. :)

**Comment by amsdard** [comment]
Thanks for reply. One more question, is this not supported yet by traefik itself or by rancher-traefik?

**Comment by rawmind0** [comment]
Hi @amsdard 

From alpine-traefik release, 1.4.0-3 traefik built in rancher integration is supported, metadata and api. Also, community-catalog is already updated. Now 3 rancher integration are available, metadata, api ( traefik built in) or external (rancher-traefik). 

Take into account that labels are different with traefik built in integration, https://docs.traefik.io/configuration/backends/rancher/#labels-overriding-default-behaviour
Metadata with longpoll is the prefered integration, it’s working so good. :)

Best regards...
