### ISSUE TITLE
Native rancher support in traefik

### ISSUE THREAD

**Issue by warroyo** [rawmind0/rancher-traefik#47]
Now that traefik supports rancher as a backend, will this continue to be maintained or will the preferred method of using traefik in rancher be to use the native support?

Also is it possible this will be modified to leverage the Native rancher support?

**Comment by rawmind0** [comment]
Hi @warroyo ,

native rancher support is already implemented in rawmind0/alpine-traefik images, take a look, https://github.com/rawmind0/alpine-traefik/issues/37#issuecomment-315788939

Logically, native rancher support in traefik would be preferred, and rancher-traefik would be discontinued if it's not useful. :)

**Comment by rawmind0** [comment]
Hi @warroyo 

In last alpine-traefik release, 1.4.0-3 traefik built in rancher integration is supported, metadata and api. Also, community-catalog is already updated. Now 3 rancher integration are available, metadata, api ( traefik built in) or external (rancher-traefik). 

Take into account that labels are different with traefik built in integration, https://docs.traefik.io/configuration/backends/rancher/#labels-overriding-default-behaviour
Metadata with longpoll is the prefered integration, it’s working so good. :)

Best regards...
