### ISSUE TITLE
Any way to only publish one domain ? 

### ISSUE THREAD

**Issue by seb2411** [rawmind0/rancher-traefik#50]
Hello,

I would like to know if, it's possible to disable the automatically generated domain name based on stack and service name, when alias is set ?

So If I set `traefik.alias: www` and `traefik.domain: example.com`, traefik only publish www.example.com

Regards,

**Comment by jrohde** [comment]
Hi @seb2411 

In case you still need this, we're using the traefik.domain.regexp label for that. 
```
traefik.enable=true
traefik.domain.regexp='your_domain_tld'
traefik.acme=true
```
Don't know if that's the correct way, but it seems to work fine ;-)

**Comment by seb2411** [comment]
Hi @jrohde 

Thank you. I will try to see if it works for me.

**Comment by rawmind0** [comment]
Please, reopen if you still have issues.
