### ISSUE TITLE
Skip Health Check

### ISSUE THREAD

**Issue by g-psantos** [rawmind0/rancher-traefik#53]
Is there a way to not filter services by their health state?

I'm trying to use Traefik with Rancher to dynamically serve GitLab Review Apps. I have GitLab CI deploying services to Rancher with the Rancher CLI. However, while I'm able to set the necessary labels (traefik.enabled, traefik.domain, etc.), I can't set health checks through the CLI. This means that whenever a Review App for a new branch is being published, I have to go in the Rancher UI and manually configure the health check, which is a bit annoying.

**Comment by rawmind0** [comment]
Not by the moment. Just services with configured health check and healthy state are published. 

I don’t understand so much what you say about rancher CLI. You could deploy and upgrade services with labels and health check from rancher CLI, you don’t need to go to UI and configure them manually. Just add health check to your rancher compose file or to your catalog definition. 

Anyway, using or not traefik, add health check to your services is a good practice. ;)
