### ISSUE TITLE
Specifing staging acme

### ISSUE THREAD

**Issue by gad0lin** [rawmind0/rancher-traefik#54]
I am testing traefik with letsencrypt in dev environment.

Unfortunately I have hit rate limit - https://letsencrypt.org/docs/rate-limits/.

I would like to switch to staging system while I test:  https://letsencrypt.org/docs/staging-environment/. 

How can I achieve that?

https://github.com/containous/traefik/blob/master/docs/configuration/acme.md
[acme]
# ...
caServer = "https://acme-staging.api.letsencrypt.org/directory"

thanks,
  Krzysztof

**Comment by aslafy-z** [comment]
This has to be done within the other repository [rawmind0/alpine-traefik](https://github.com/rawmind0/alpine-traefik), I made a pull-request https://github.com/rawmind0/alpine-traefik/pull/47
**Merged and released**:  [rawmind0/alpine-traefik@1.3.8-4](https://github.com/rawmind0/alpine-traefik/releases/tag/1.3.8-4)

**Comment by rawmind0** [comment]
Thanks @aslafy-z ....
