### ISSUE TITLE
Traefik multiple frontend rule not working

### ISSUE THREAD

**Issue by thinhnd8752** [rawmind0/rancher-traefik#55]
I configure rancher container with label like this:
```
traefik.enabled: true
traefik.ui.port: 3000
traefik.ui.frontend.rule: Host:ui.example.com
traefik.api.port: 5000
traefik.api.frontend.rule: Host:api.example.com
```

But seem like rancher-traefik not understand my configure even traefik support multiple frontend rule config

How can I achieve that ?
Thanks for reading

**Comment by rawmind0** [comment]
Hi @thinhnd8752 ...

These labels are not supported in this image. Take a look to the README.md to see what labels are supported and how this image works.

This image is just necessary if you use traefik with external rancher integration. Last versions of rawmind/alpine-traefik implements the built in traefik rancher integration, api and metadata. Metadata is the recommended way to do it, and you don’t need this image. Check traefik rancher integration to see what labels are supported. 

Best regards...
