### ISSUE TITLE
wrong number of args for getStickinessCookieName: want 2 got 1

### ISSUE THREAD

**Issue by trauts2** [rawmind0/rancher-traefik#57]
Using the latest rawmind/alpine-traefik:1.4.2-0 with Rancher 1.6.11 I am unable to get stickiness working.  The sceenshot below shows the labels added to the service

https://screencast.com/t/3bfGG7SyAjDG

Here is what I see in traefik logs:

```
11/18/2017 1:19:01 AMtime="2017-11-18T07:19:01Z" level=error msg="template: :14:24: executing "" at <getStickinessCookieN...>: wrong number of args for getStickinessCookieName: want 2 got 1"
11/18/2017 1:19:01 AMtime="2017-11-18T07:19:01Z" level=info msg="Skipping empty Configuration for provider rancher"
```
Any suggestions much appreciated

**Comment by rawmind0** [comment]
Hi @trauts2 ...

this image doesn't manage these labels.  Your are using traefik rancher built in integration. You need to open an issue at traefik repo. Seems a bug with this `traefik.backend.loadbalancer.stickiness.cookieName` label and traefik rancher built in integration.

**Comment by trauts2** [comment]
Thanks Raul!  I see you also posted that bug AND a PR.  I really appreciate it.

What would it take for me to use this before it makes it's way into a release of both traefik and this integration?  Make a custom build myself, push it to a repository I own, and use this new version in Rancher?

**Comment by trauts2** [comment]
Now that the fix has been merged to master, what are the steps for me to test this in Rancher?  Sorry if this is a dumb question, I'm new to golang

**Comment by trauts2** [comment]
nevermind, the deprecated method works fine.  Thanks again.

**Comment by rawmind0** [comment]
New version released with issue solved. rawmind/traefik:1.4.4-1

Updated Rancher community catalog traefik version
