### ISSUE TITLE
Configuration keeps resetting

### ISSUE THREAD

**Issue by khusseini** [rawmind0/rancher-traefik#58]
Hey there,

since today we are experiencing a weird issue with traefik for rancher. 
The configuration seems to be cleared every few minutes, rendering our services unusable.
There are not errors in the logs whatsoever.

Does anyone else encounter this issue?

**Comment by rawmind0** [comment]
Hi @khusseini ,

how are you running traefik?? versions?? rancher integration??...

**Comment by khusseini** [comment]
Sorry for the late reply, I was on holiday. I am using Traeffik within rancher and installed it using the catalog. Latest version 1.4.5-rancher1. I am not sure if this is the right repo for this ticket though, I get confused by the many traefik repositories here on github ;)

I'm using the external configuration of the catalog and supplied my API keys as well (just in case they are still needed). It is a strange behaviour, sometimes the config stays for several days and then without reason suddenly disappears and comes back every half an hour or so.

**Comment by rawmind0** [comment]
If you have the issue with traefik external integration, yes, this is the correct repo to open the issue. ;)

Have you seen something at traefik logs?? Could you please provide the logs of rancher-template?? `/opt/tools/rancher-template/log/rancher-template.log`

**Comment by khusseini** [comment]
Unfortunately the file could not be found in any of the traefik containers :/
the stdout/stderr logs only show the HTTP access logs.

I noticed that I have two traefik container running for some reason, is this an expected behaviour?

```
59c547c2f8e1        rawmind/alpine-traefik:1.4.5-0                                                                "/.r/r /bin/bash -c $"   8 hours ago         Up 21 minutes                                                                  r-traefik-traefik-1-924e17f5
b2379487a203        rawmind/alpine-traefik:1.4.5-0                                                                "/.r/r /bin/bash -c $"   2 weeks ago         Up 2 weeks                                                                     r-traefik-traefik-1-08ab3cc0
```

Strange that one of them has been up for 2 weeks already. Should I try to kill it and restart the whole thing?

**Comment by rawmind0** [comment]
It's strange, if you are running traefik with `external` rancher integration, a sidekick should be running `rawmind/rancher-traefik:1.4.4-3` that provides rancher-template. Are you using `external` rancher integration or builtin `api` or `metadata`??

**Comment by khusseini** [comment]
Also I noticed that the `traefik-traefik-traefik-conf` container uses a different image than the `traefik-traefik`
![screenshot from 2018-01-09 10-35-31](https://user-images.githubusercontent.com/1408107/34714536-041fed4a-f52a-11e7-9ffc-7ca5946237e4.png)

**Comment by rawmind0** [comment]
yes, it's expected....At `traefik_traefik_1` container, isn't it file `/opt/tools/rancher-template/log/rancher-template.log`??

**Comment by khusseini** [comment]
I'm using the external configuration so that I can use custom domains.
After I removed the "old" container, and restarted the whole stack, only the `traefik_traefik_1` is running but the other two have been started with one-shot. So far so good, the configuration has not been reset yet in the last 10 minutes

**Comment by rawmind0** [comment]
This is expected too... Sidekicks are configured as run-once... 
With this configuration, rancher-template is the responsible to update traefik config, and its log info should be at `/opt/tools/rancher-template/log/rancher-template.log` file.

**Comment by khusseini** [comment]
Sorry, file not found :/

```
$ docker exec -ti r-traefik-traefik-1-924e17f5 bash                                                
bash-4.3$ cat /opt/tools/rancher-template/log/rancher-template.log                                                                     
cat: can't open '/opt/tools/rancher-template/log/rancher-template.log': No such file or directory
```

**Comment by rawmind0** [comment]
Oh, my fault on this, it's from `rawmind/rancher-traefik:1.4.4-4`. Could you please update your traefik-conf image to `rawmind/rancher-traefik:1.4.4-4`??

**Comment by rawmind0** [comment]
I've upgraded community catalog traefik package, please try with it.
https://github.com/rancher/community-catalog/pull/716
