### ISSUE TITLE
Rate limiting in Traefik 1.5

### ISSUE THREAD

**Issue by Hermsi1337** [rawmind0/rancher-traefik#59]
Hey @rawmind0 ,

Traefik 1.5 supports rate limiting based on client ip:
https://github.com/containous/traefik/pull/2034

Docs here:
http://v1-5.archive.docs.traefik.io/configuration/commons/#rate-limiting

It would be an awesome feature if it is implemented in this dynamic conf service.
That way you could configure rate limiting using service labels.

What do you think?

Regards,

Hermsi

**Comment by rawmind0** [comment]
Hey @Hermsi1337 ,

sure, nice to have feature. A PR would be appreciated. :)

**Comment by rawmind0** [comment]
Hi @Hermsi1337 , thanks for the PR....

I'll try to review it asap... :)

**Comment by rawmind0** [comment]
Reviewed PR, please take a look...

**Comment by Hermsi1337** [comment]
I made the requested changes. 

Hope that everything's fine now.

**Comment by rawmind0** [comment]
Released rawmind/rancher-traefik:1.5.0-0
