### ISSUE TITLE
Adjusting the request timeout values

### ISSUE THREAD

**Issue by trauts2** [rawmind0/rancher-traefik#64]
This PR describes a feature we would like to use:
containous/traefik#1873

We have several pages which take longer to complete, and traefik is periodically timing out too early. Is it possible to access this configuration somehow to bump up the timeout values?  We don't want the request to timeout for a very long time, on the order of 10 minutes.

Thanks!

Stu

I may have posted this in the wrong group previously: 
https://github.com/rawmind0/alpine-traefik/issues/78

**Comment by rawmind0** [comment]
Hi @trauts2 , 
rawmind0/alpine-traefik is the good place for this issue.
