### ISSUE TITLE
How to enable Let's Encrypt

### ISSUE THREAD

**Issue by f3l1x** [rawmind0/rancher-traefik#65]
Hi, thanks for the traefik for Rancher.

I have a problem with generating certificates. I'm quite confused about `traefik.domain`, `rancher.domain`, `onHostRule`.

Let's say I have a service with labels:

```
traefik.enable=true
traefik.port=80
traefik.frontend.rule | PathPrefix:/,Host:mydomain.tld
```

What about labels `traefik.acme`, `traefik.domain`? Are they needed?

Currenty, routing works, 80 port works, 443 port does not work with certificates.

Thanks.

**Comment by rawmind0** [comment]
Hi @f3l1x,

if you are deploying traefik into rancher from community package, you have 3 distinct options of rancher integration, api and metadata (built in in traefik) or external (using this image rancher-traefik). Services labels are different for distinct integrations. 

- If you are using api or metadata, this service labels are available, https://docs.traefik.io/configuration/backends/rancher/#labels-overriding-default-behaviour. 
- If you are using external (you are using this image), just service labels defined at [README.md](https://github.com/rawmind0/rancher-traefik) could be used. `traefik.frontend.rule` doesn't exist in that case. `traefik.domain` label is used to construct frontend rule on the form `<service_name>.<stack_name>.<traefik.domain>`. `traefik.acme` is used to enable letsencrypt certificates generation for the service, but it need to able and https  at [alpine-traefik](https://github.com/rawmind0/alpine-traefik)

**Comment by f3l1x** [comment]
I see. Thanks a lot for the explanation.

I'm using Traefik with metadata integration. So it means I can use this configuration:

```
traefik.enable=true
traefik.port=80
traefik.frontend.rule=PathPrefix:/api
```

Will Traefik generates Let'sEncrypt certificates? Or I have to provide `traefik.domain=mydomain.tld` or `Host:mydomain.tld` also?

One more thing, if I disable `onHostRule`, will Traefik generates Let'sEncrypt certificates properly?

**Comment by rawmind0** [comment]
I guess you need at least one host rule to be able traefik generate letsencrypt certificates. `traefik.frontend.rule` has a default value, https://docs.traefik.io/configuration/backends/rancher/#labels-overriding-default-behaviour , but if it's ovewritten with path rule, host rule would be needed to generate certificate.
`traefik.frontend.rule=PathPrefix:/api,Host:mydomain.tld`

I guess you need [onHostRule](https://docs.traefik.io/configuration/acme/#onhostrule), but you could test without it. :)

**Comment by f3l1x** [comment]
Thanks @rawmind0. It helps. Good work on this repository.

**Comment by mikemix** [comment]
I’m sorry for continuing this topic but it is quite fresh and already high in google index. 

My Traefik does not expose 443 port at all and I suspect the “enable https” option needs to be set to true. If so the ssl certificate and key are required, but I don’t know which domain certificate to provide ti finally enable LetsEncrypt for my containers.

**Comment by emcniece** [comment]
@mikemix from what I understand, the "ssl certificate and key" required are the defaults that are served when no matching cert is found. If you don't provide those, Traefik will serve... some other default? It's certainly not valid, whatever it is.

You are correct in that the "enable https" option needs to be true. I think it's misleading to say that "ssl certificate and key are required" because I never add these and it works fine.
