### ISSUE TITLE
How to connect KV storage

### ISSUE THREAD

**Issue by volatilemolotov** [rawmind0/rancher-traefik#66]
Hello, 

Is it possible to easily connect traefik to Consul on rancher? Using env or something?
Im trying to avoid editing your image. 

Thanks

**Comment by rawmind0** [comment]
Hi @volatilemolotov12 ,

this image is just for integrate traefik and rancher. The issue should be on rawmind0/alpine-traefik. 

Anyway, consul configuration is not supported by rawmind0/alpine-traefik, just support rancher, k8s and file integration. PR would be pretty appreciated if you like to add consul support. :)

**Comment by volatilemolotov** [comment]
I will certainly try. I am doing other things right now but i plan to revisit this. 

We can close this issue for now.
