### ISSUE TITLE
Error: Name does not end in a public suffix

### ISSUE THREAD

**Issue by samouds** [rawmind0/rancher-traefik#68]
Hello,

I get this error when I run the 1.5.3 rancher template version for all my containers. (My rancher version is : 1.6.5)

```
level=error msg="Error getting ACME certificates [xxxxxx.xxxxxxx.rancher.internal] : cannot obtain certificates map[xxxxxx.xxxxxxx.rancher.internal:acme: Error 400 - urn:acme:error:malformed - Error creating new authz :: Name does not end in a public suffix]"
```

My config : 
```
      TRAEFIK_ACME_CASERVER: https://acme-v01.api.letsencrypt.org/directory
      TRAEFIK_ACME_CHALLENGE: http
      TRAEFIK_ACME_CHALLENGE_HTTP_ENTRYPOINT: http
      TRAEFIK_ACME_EMAIL: mail@mail.com
      TRAEFIK_ACME_ENABLE: 'true'
      TRAEFIK_ACME_ONHOSTRULE: 'true'
      TRAEFIK_ADMIN_AUTH_METHOD: basic
      TRAEFIK_ADMIN_AUTH_USERS: ''
      TRAEFIK_ADMIN_ENABLE: 'true'
      TRAEFIK_ADMIN_PORT: '8000'
      TRAEFIK_ADMIN_SSL: 'false'
      TRAEFIK_ADMIN_STATISTICS: '10'
      TRAEFIK_CONSTRAINTS: ''
      TRAEFIK_FILE_ENABLE: 'false'
      TRAEFIK_HTTPS_COMPRESSION: 'true'
      TRAEFIK_HTTPS_ENABLE: only
      TRAEFIK_HTTPS_PORT: '443'
      TRAEFIK_HTTP_COMPRESSION: 'true'
      TRAEFIK_HTTP_PORT: '80'
      TRAEFIK_INSECURE_SKIP: 'false'
      TRAEFIK_RANCHER_ENABLE: 'true'
      TRAEFIK_RANCHER_HEALTHCHECK: 'false'
      TRAEFIK_RANCHER_MODE: metadata
```

Do you have any idea ?

Thanks.

**Comment by rawmind0** [comment]
Hi @samouds ,

it's an error from letsencrypt, you couldn't use internal domain names.

**Comment by samouds** [comment]
Hello @rawmind0 

Thanks, but how can I redirect web traffic to my containers ? i was using 1.3.6 before and everything was working as expected.

Do I need to change TRAEFIK_RANCHER_MODE to external ?

**Comment by rawmind0** [comment]
I don't think it's a question of rancher integration mode. 

Traffic is already redirected to your containers, but you couldn't use internal domain names with ACME support. If you want to use letsencrypt, you need to use pubic domain names.

**Comment by samouds** [comment]
for example I have this container with these labels :  

traefik.domain=mydomain.com
traefik.enable=true
traefik.port=8080

but I get the same error.
