### ISSUE TITLE
Traefik doesn't send data to Prometheus 

### ISSUE THREAD

**Issue by cr0hn** [rawmind0/rancher-traefik#70]
I configured Traefik in Rancher as Doc says:

![rancher](https://user-images.githubusercontent.com/4076390/37876984-9af82902-3054-11e8-8ab5-526e8bcca878.png)

But It's appear that Traefik doesn't send data to Prometheus. 'Traefik*' index is not listed in Prometheus:

![prometheus_time_series_collection_and_processing_server](https://user-images.githubusercontent.com/4076390/37877016-ee99a61c-3054-11e8-967d-95a9d4255cac.png)

To ensure I followed this tutorial: https://www.brianchristner.io/how-to-monitor-traefik-reverse-proxy-with-prometheus/

But, the Graphana Dashboard is empty:

![grafana_-_traefik_realtime_stats_y_new_issue_ _rawmind0_rancher-traefik](https://user-images.githubusercontent.com/4076390/37877028-2a6f47d2-3055-11e8-9be8-c7b0a5756e05.png)

I'm doing something wrong?

**Comment by rawmind0** [comment]
Hi @cr0hn,

Traefiks doesn't send metrics to prometheus. It just expose metrics to prometheus could pull them. How are you configuring static_config on your prometheus?? It has to be configured to traefik admin port , 8000 by default. 

Best regards..

**Comment by rawmind0** [comment]
Using prometheus community-catalog, works fine adding this config to `scrape_configs:` section at `/etc/prom-conf/prometheus.yml`
```
- job_name: 'TraefikMetrics'
  static_configs:
    - targets:
      - '<TRAEFIK_SERVICE>.<TRAEFIK_STACK>:<TRAEFIK_ADMIN_PORT>'
```

**Comment by cr0hn** [comment]
Nice! Thank you very much. I'll fork the official Prometheus and add that. Thx!
