### ISSUE TITLE
Port 80 is not chosen as default

### ISSUE THREAD

**Issue by spawnia** [rawmind0/rancher-traefik#71]
When trying to register a service running on port 80. according to the `Readme` it should use that as a default. In fact, it did not register the service with the following rules:
````
User | traefik.frontend.rule | Host:franke.tech
User | traefik.enable | true
User | traefik.domain | franke.tech
User | traefik.acme | true
````

When i added `frontend.port=80` it finally picked up the service. It would be nice to either implement the default port or fix the readme to mention the port as a required label. Looking at the traefik docs, they do not mention there being a default port for the rancher backend.

**Comment by rawmind0** [comment]
What integration are you using for traefik?? 

This image is just used if you choose `external` integration at rancher community-catalog package. Using `external` labels and default values are shown at this repo README.md file. `frontend.port` label just exists if you are using `api` or `metadata` integration, take a look at traefik doc page https://docs.traefik.io/configuration/backends/rancher/#labels-overriding-default-behaviour

Could read all this info at community-catalog package, https://github.com/rancher/community-catalog/tree/master/templates/traefik/20

**Comment by spawnia** [comment]
I was in fact using the `metadata` integration. The update to the doc page makes the difference clear, thank you very much.
