### ISSUE TITLE
Any reason why DNS-01 is not offered in the catalog?

### ISSUE THREAD

**Issue by EugenMayer** [rawmind0/rancher-traefik#74]
Its about this merged PR https://github.com/kubernetes/charts/pull/1299

Seems like it has been release with 1.5.0

Docs: https://docs.traefik.io/configuration/acme/ .. see `[acme.dnsChallenge]`

I guess we would need to add those new values to the catalog:

1) `provider` (full list :https://docs.traefik.io/configuration/acme/#provider )
2) API_USER
3) API_TOKEN

I would limit the list of supported `providers` to the actual user/token authenticated, since otherwise this feature would become a lot more complicated, espcially in the catalog UI.

I understand, that providing those individual ENV vars is kind of a hazzle in the docker-compose.tpl - so what about creating a script which takes our general provider USER/TOKEN attribtues as ENV params and then exports the corresponding ENV vars in a big switch case and creates /.acme_env

Before starting `traefik` we source that env file `. /.acme_env && traefik` and thats about it.
This way we could keep out the logic out of the docker-compose.tpl and maybe we even find such a script already.

**Comment by EugenMayer** [comment]
Alternative b would be ( easier ) let someone select the provider ( which then goes in to the .toml ) and then create 10 fields: ENV1_NAME, ENV1_VALUE .. and link to https://docs.traefik.io/configuration/acme/#provider

Then people could set the proper env variables directly and we could support about any provider.

Maybe a easier way is to have one field "ENV_VARS" with the syntax name=key; and the split and add those in the docker-compose.tpl using go-tpl.

For reference, the current ACME defintion can be found here https://github.com/rancher/community-catalog/blob/master/templates/traefik/20/docker-compose.yml.tpl#L57
**Question**: are those ENV vars picked up by https://github.com/rawmind0/rancher-tools somehow or directly in the go-template process. Could not yet find those - being aware of https://github.com/rawmind0/rancher-traefik/blob/master/root/opt/tools/rancher-template/tmpl/traefik.tmpl

I found `traefik.toml.sh` in the container, but not its actual github source

**Comment by EugenMayer** [comment]
Important current bug which could be blocking a mix of http / dns challenge configs: https://github.com/containous/traefik/issues/3302

**Comment by rawmind0** [comment]
Hi @EugenMayer, 

this issue should be opened at [rawmind0/alpine-traefik](https://github.com/rawmind0/alpine-traefik) repo. This image is just used for `external` traefik rancher integration. 

`traefik.toml.sh` is part of [rawmind0/alpine-traefik](https://github.com/rawmind0/alpine-traefik) image. You could find it at https://github.com/rawmind0/alpine-traefik/blob/master/root/opt/traefik/bin/traefik.toml.sh. 

DNS-01 is not offered at the catalog due to a security problem that was reported. May be it's solved now and could be added. [rawmind0/alpine-traefik](https://github.com/rawmind0/alpine-traefik) is already prepared to do it, env variables to manage acme challenge, parameters and logic is already added.
```
- TRAEFIK_ACME_ENABLE="false"							# Enable/disable traefik ACME feature. [acme](https://docs.traefik.io/configuration/acme/)
- TRAEFIK_ACME_CHALLENGE=""                             # Set http | dns to activate traefik acme challenge mode. 
- TRAEFIK_ACME_CHALLENGE_HTTP_ENTRYPOINT="http"         # Set traefik acme http challenge entrypoint. [acme http challenge](https://docs.traefik.io/configuration/acme/#acmehttpchallenge)
- TRAEFIK_ACME_CHALLENGE_DNS_PROVIDER=""                # Set traefik acme dns challenge provider. You need to manually add configuration env variables accordingly the dns provider you use. [acme dns provider](https://docs.traefik.io/configuration/acme/#provider)
- TRAEFIK_ACME_CHALLENGE_DNS_DELAY=""                # Set traefik acme dns challenge delayBeforeCheck. [acme dns challenge](https://docs.traefik.io/configuration/acme/#acmednschallenge)
- TRAEFIK_ACME_EMAIL="test@traefik.io"					# Default email
- TRAEFIK_ACME_ONHOSTRULE="true"						# ACME OnHostRule parameter
- TRAEFIK_ACME_CASERVER="https://acme-v01.api.letsencrypt.org/directory"						# ACME caServer parameter
```

**Comment by rawmind0** [comment]
Please, feel free to reopen this issue at [rawmind0/alpine-traefik](https://github.com/rawmind0/alpine-traefik)

**Comment by EugenMayer** [comment]
ah well, since that is a blocker for me in isolated rancher envs, i will follow up in alpine-traefik. Do you have any links to the sec-issues you mentioned so i can follow up?
